In [7]:
import cv2
print("--------------------------------3D Image-----------------------------")
img=cv2.imread('D:\\girl.jpg',1)
print("Images for Computer: \n",img)
print("Type of Image: ",type(img))
print("Image Shape: ",img.shape)
print("Image Size: ",img.size)# image_shape(490 * 376 * 3) => img_size = 552720
print("Image Dimensions: ",img.ndim)
print("Image Data-Type: ",img.dtype)
print("--------------------------------2D Image-----------------------------")
img=cv2.imread('D:\\girl.jpg',0)
print("Images for Computer: \n",img)
print("Type of Image: ",type(img))
print("Image Shape: ",img.shape)
print("Image Size: ",img.size)# image_shape(490 * 376 ) => img_size = 184240
print("Image Dimensions: ",img.ndim)
print("Image Data-Type: ",img.dtype)

--------------------------------3D Image-----------------------------
Images for Computer: 
 [[[ 19  18  22]
  [ 19  18  22]
  [ 19  18  22]
  ...
  [ 22  23  27]
  [ 22  23  27]
  [ 21  22  26]]

 [[ 19  18  22]
  [ 19  18  22]
  [ 19  18  22]
  ...
  [ 21  22  26]
  [ 21  22  26]
  [ 21  22  26]]

 [[ 19  18  22]
  [ 19  18  22]
  [ 19  18  22]
  ...
  [ 21  22  26]
  [ 21  22  26]
  [ 21  22  26]]

 ...

 [[151 168 224]
  [152 169 225]
  [153 170 226]
  ...
  [ 11  12  16]
  [ 10  11  15]
  [  9  10  14]]

 [[155 176 227]
  [150 171 222]
  [153 174 226]
  ...
  [ 15  13  19]
  [ 14  12  18]
  [ 13  11  17]]

 [[155 176 227]
  [150 171 222]
  [153 174 226]
  ...
  [ 15  13  19]
  [ 14  12  18]
  [ 13  11  17]]]
Type of Image:  <class 'numpy.ndarray'>
Image Shape:  (490, 376, 3)
Image Size:  552720
Image Dimensions:  3
Image Data-Type:  uint8
--------------------------------2D Image-----------------------------
Images for Computer: 
 [[ 19  19  19 ...  24  24  23]
 [ 19  19  19 ...  2