In [51]:
import cv2
import numpy as np
import matplotlib.pyplot as plt
img=cv2.imread('D:\\4.1.05.tiff')
# edegs=np.array(([-1,-1,-1],[-1,8,-1],[-1,-1,-1]),np.float32)
# box_blur=np.array(([22,22,22],[22,22,22],[22,22,22]),np.float32)/484
# sharpen=np.array(([0,-1,0],[-1,5,-1],[0,-1,0]),np.float32)
print(box_blur)
cam=cv2.VideoCapture(0)
while True:
    chek,frame=cam.read()   
    output=cv2.filter2D(frame,-1,sharpen)
    cv2.imshow('Edges',output)
    cv2.imshow('orignal',frame)
    if cv2.waitKey(1)==27:
        break
cv2.destroyAllWindows()
cam.release()


[[0.04545455 0.04545455 0.04545455]
 [0.04545455 0.04545455 0.04545455]
 [0.04545455 0.04545455 0.04545455]]
